<div class="container">
    <div class="row mb-2 mt-4 align-items-center">
        <div class="col-12">
            <img src="public/views/resources/img/banner.png" width="200" height="60" class="float-left img-fluid" alt="logo-libro-reclamos-hnseb">
            <img src="public/views/resources/img/susalud.png" width="250" height="60" class="float-right img-fluid my-5" alt="logo-susalud">
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-sm-12 col-md-12 col-12">
            <div class="callout callout-info">
                <h5 class="font-weight-bold"><i class="fas fa-user"></i> Estimado Usuario:</h5>
                Ponemos a tu disposición nuestro <span class="font-weight-bold">Libro de Reclamaciones en Salud Virtual</span>, para que puedas registrar tu reclamo con respecto a nuestro servicio como institución de Salud, acorde al <span class="font-weight-bold">Decreto Supremo N° 002-2019-SA</span>
            </div>
        </div>


    </div>
    <div class="row mb-3">
        <div class="col-sm-12 col-md-12 col-12">
            <span class="text-danger font-weight-bold">(*) Completa correctamente los campos requeridos en el formulario.</span>
        </div>
    </div>
</div>
<div class="container">
    <form action="" method="post" id="formRegReclamo">
        <input type="hidden" name="autogenerated" id="autogenerated" value="<?php date_default_timezone_set('America/Lima');
                                                                            $currentDate = date("YmdHis");
                                                                            echo 'LRV' . $currentDate . sha1(time()); ?>">

        <div class="card card-info">
            <div class="card-header">
                <h5 class="card-title m-0 font-weight-bold">1. Identificación del Usuario o Tercero legitimado. </h5>&nbsp;&nbsp;<i class="fas fa-users"></i>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="form-group">
                            <label>Tipo de Documento:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                                </div>
                                <select class="form-control" name="tDocUsuario" id="tDocUsuario">
                                    <option value="0" selected>Seleccione Tipo Doc</option>
                                    <?php
                                    $opcionDoc = 1;
                                    $TDocUsuario = ControladorUtilitarios::ctrListarTipoDoc($opcionDoc);
                                    foreach ($TDocUsuario as $key => $value) {
                                        echo '<option value="' . $value["idTipoDoc"] . '">' . $value["abrvTipDoc"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="form-group">
                            <label>Número de Documento:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese N° de documento" autocomplete="off" name="nDocUsuario" id="nDocUsuario" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 d-none" id="btnDNIUsuario">
                        <div class="form-group">
                            <label>Consulta:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <button type="button" class="btn btn-block btn-primary" id="btnDNIU"><i class="fas fa-search"></i>&nbsp;Buscar DNI o RUC</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="rsUsuarioBlock">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label>Razón Social:<span class="text-danger">&nbsp;(Solo si selecciona Tipo de Documento : RUC)*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese nombres" autocomplete="off" id="rsUsuario" name="rsUsuario">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" id="UsuarioNatural">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Nombre:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese nombres" autocomplete="off" id="nomUsuario" name="nomUsuario" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Apellido Paterno:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese apellido paterno" autocomplete="off" id="APUsuario" name="APUsuario" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Apellido Materno:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese apellido paterno" autocomplete="off" id="AMUsuario" name="AMUsuario" required>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="form-group">
                            <label>Sexo:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-venus-mars"></i></span>
                                </div>
                                <select class="form-control" name="sexUsuario" id="sexUsuario">
                                    <option value="0">Seleccione su sexo</option>
                                    <?php
                                    $sexUsuario = ControladorUtilitarios::ctrListarTipSexo();
                                    foreach ($sexUsuario as $key => $value) {
                                        echo '<option value="' . $value["idSexo"] . '">' . $value["descSexo"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Correo Electrónico:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-at"></i></span>
                                </div>
                                <input type="email" class="form-control" placeholder="Ingrese su correo electrónico" autocomplete="off" id="emailUsuario" name="emailUsuario" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Teléfono || Celular:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone-volume"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese N°teléfono o celular" autocomplete="off" name="telefUsuario" id="telefUsuario" required>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Departamento:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-map-marked-alt"></i></span>
                                </div>
                                <select class="form-control" id="DepUsuario" name="DepUsuario">
                                    <option value="0">Seleccione Departamento</option>
                                    <?php
                                    $DepUsuario = ControladorUtilitarios::ctrListarDepartamento();
                                    foreach ($DepUsuario as $key => $value) {
                                        echo '<option value="' . $value["idDepartamento"] . '">' . $value["descDepartamento"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Provincia:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-map-marked-alt"></i></span>
                                </div>
                                <select class="form-control" id="ProvUsuario" name="ProvUsuario">
                                    <option value="0">Seleccione Provincia</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Distrito:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-map-marked-alt"></i></span>
                                </div>
                                <select class="form-control" id="DistUsuario" name="DistUsuario">
                                    <option value="0">Seleccione Distrito</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label>Domicilio:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-location-arrow"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese su domicilio" autocomplete="off" id="DomUsuario" name="DomUsuario" required>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-info">
            <div class="card-header">
                <h5 class="card-title m-0 font-weight-bold">2. Identificación de quién presenta el reclamo (En caso de ser usuario afectado no es necesario su llenado). </h5>&nbsp;&nbsp;<i class="fas fa-hands-helping"></i>
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-7 col-xl-7">
                        <label>¿Es el familiar o representante del usuario afectado quien presenta el reclamo?</label>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="input-group">
                            <div class="icheck-dark d-inline">
                                <input type="radio" id="radiorep1" name="repCon" value="1">
                                <label for="radiorep1"> SI
                                </label>&nbsp;&nbsp;
                            </div>
                            <div class="icheck-dark d-inline">
                                <input type="radio" id="radiorep2" name="repCon" value="2">
                                <label for="radiorep2"> NO
                                </label>
                            </div>
                            <input type="hidden" name="representante" id="representante">
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="bloqueRep1">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="form-group">
                            <label>Tipo de Documento:<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                                </div>
                                <select class="form-control" id="tDocRep" name="tDocRep">
                                    <option value="0">Seleccione Tipo Doc</option>
                                    <?php
                                    $opcionDoc2 = 2;
                                    $TDocUsuario2 = ControladorUtilitarios::ctrListarTipoDoc($opcionDoc2);
                                    foreach ($TDocUsuario2 as $key => $value) {
                                        echo '<option value="' . $value["idTipoDoc"] . '">' . $value["abrvTipDoc"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Número de Documento:<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese N° de documento" autocomplete="off" id="nDocRep" name="nDocRep">
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3" id="btnDNIRepresentante">
                        <div class="form-group">
                            <label>Consulta:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <button type="button" class="btn btn-block btn-primary" id="btnDNIRep"><i class="fas fa-search"></i>&nbsp;Buscar con DNI o RUC</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="RepJuridica">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label>Razón Social:<span class="text-danger">&nbsp;(Solo si selecciona Tipo de Documento : RUC)*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese nombres" autocomplete="off" id="rsRep" name="rsRep">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="RepNatural">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Nombre:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese nombres" autocomplete="off" id="nomRep" name="nomRep" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Apellido Paterno:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese apellido paterno" autocomplete="off" id="APRep" name="APRep" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Apellido Materno:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-signature"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese apellido paterno" autocomplete="off" id="AMRep" name="AMRep" required>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row d-none" id="bloqueRep2">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Correo Electrónico<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-at"></i></span>
                                </div>
                                <input type="email" class="form-control" placeholder="Ingrese correo electrónico" autocomplete="off" id="emailRep" name="emailRep">
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Teléfono || Celular<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone-volume"></i></span>
                                </div>
                                <input type="tel" class="form-control" placeholder="Ingrese teléfono o celular" autocomplete="off" id="telefRep" name="telefRep">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="bloqueRep3">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label>Domicilio:<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-location-arrow"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Ingrese su dirección" autocomplete="off" id="DomRep" name="DomRep">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-info">
            <div class="card-header">
                <h5 class="card-title m-0 font-weight-bold">3. Datos del reclamo. </h5>&nbsp;&nbsp;<i class="fas fa-users"></i>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <label>Tipo de Usuario:<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-hospital"></i></span>
                                </div>
                                <select class="form-control" id="tipoUsuario" name="tipoUsuario">
                                    <option value="0">Seleccione tipo de usuario</option>
                                    <?php
                                    $TipUsuario = ControladorUtilitarios::ctrListarTiposUsuarios();
                                    foreach ($TipUsuario as $key => $value) {
                                        echo '<option value="' . $value["idTipUsuario"] . '">' . $value["descTipUsuario"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
                        <div class="form-group">
                            <label>Fecha de Ocurrencia:<span class="text-danger">&nbsp;*</span></label>

                            <div class="input-group date" id="fechaOcu" data-target-input="nearest">
                                <div class="input-group-append" data-target="#fechaOcu" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                                <input type="text" name="cajaFecha" id="cajaFecha" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask autocomplete="off" placeholder="dd/mm/yyyy" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <input type="hidden" name="fcomparacion" id="fcomparacion" value="<?php date_default_timezone_set('America/Lima');
                                                                                                $fechaActual = date('Y-m-d');
                                                                                                echo $fechaActual; ?>">
                            <label>Derecho en Salud afectado :<span class="text-danger">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fab fa-resolving"></i></span>
                                </div>
                                <select class="form-control" id="recCG" name="recCG">
                                    <option value="0">Seleccione el derecho afectado</option>
                                    <?php
                                    $CGeneral = ControladorUtilitarios::ctrListarDerechosSalud();
                                    foreach ($CGeneral as $key => $value) {
                                        echo '<option value="' . $value["idDerecho"] . '">' . $value["descDerechoSal"] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8">
                        <div class="form-group">
                            <label>Causa específica del reclamo:<span class="text-danger font-weight-bolder">&nbsp;*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fab fa-resolving"></i></span>
                                </div>
                                <select class="form-control" id="recCE" name="recCE">
                                    <option value="0">Seleccione la causa específica del reclamo</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label>Detalle del Reclamo:<span class="text-danger">&nbsp;* (1500 caracteres permitidos)</span></label>
                            <textarea class="form-control" rows="10" placeholder="Ingrese el detalle textual de su reclamo." id="detReclamo" name="detReclamo" maxlength="1500" required></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card card-info">
            <div class="card-header">
                <h5 class="card-title m-0 font-weight-bold">4. Autorizo notificación del resultado del reclamo al e-mail consignado. (Marcar) </h5>&nbsp;&nbsp;<i class="fas fa-at"></i>
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                        <div class="input-group">
                            <div class="icheck-dark d-inline">
                                <input type="radio" id="radioauto1" name="repAuto" value="1" checked>
                                <label for="radioauto1"> SI
                                </label>&nbsp;&nbsp;
                            </div>
                            <div class="icheck-dark d-inline">
                                <input type="radio" id="radioauto2" name="repAuto" value="0">
                                <label for="radioauto2"> NO
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <center>
            <button type="btn" class="btn btn-primary btn-lg mb-3 btnRegistro" id="btnEnviarReclamo">REGISTRAR</button>
        </center>
        <?php
        $registroReclamo = new ControllerReclamo;
        $registroReclamo->ctrRegistrarReclamo();
        ?>
    </form>
</div>