<?php
class ControllerReclamo
{
    static public function ctrRegistrarReclamo()
    {
        if (isset($_POST["autogenerated"]) && isset($_POST["detReclamo"])) {
            if (
                preg_match('/^[0-9]+$/', $_POST["tDocUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["sexUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["DepUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["ProvUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["DistUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["tDocRep"]) &&
                preg_match('/^[0-9]+$/', $_POST["tipoUsuario"]) &&
                preg_match('/^[0-9]+$/', $_POST["recCG"]) &&
                preg_match('/^[0-9]+$/', $_POST["recCE"])
            ) {
                date_default_timezone_set('America/Lima');

                $fechaRegReclamo = date("Y-m-d");
                $horaRegReclamo = date("H:i:s");

                // $horaRegReclamo = date('H:i:s');
                $codigoAutogen = $_POST["autogenerated"];


                $fOcurrencia1 = $_POST["cajaFecha"];
                $datefOcurrencia1 = str_replace('/', '-', $fOcurrencia1);
                $fechaOcurrencia = date('Y-m-d', strtotime($datefOcurrencia1));
                if ($_POST["representante"] == 1 && $_POST["tDocRep"] == 0) {
                    echo '<script>
                    Swal.fire({
                    icon: "error",
                    title: "Ingrese todos sus datos correctamente",
                    showConfirmButton: false,
                    timer: 2500
                    });
                    function redirect(){
                        window.location = "registro-reclamo";
                    }
                    setTimeout(redirect,2500);
                    // document.getElementById("formRegReclamo").reset();
                    </script>';
                } elseif ($_POST["representante"] == 1 && $_POST["tDocRep"] > 0) {
                    $datos = array(
                        "fechaReclamo" => $fechaRegReclamo,
                        "horaReclamo" => $horaRegReclamo,
                        "tipoDoc" => $_POST["tDocUsuario"],
                        "nDoc" => $_POST["nDocUsuario"],
                        "razonSocial" => $_POST["rsUsuario"],
                        "nombres" => $_POST["nomUsuario"],
                        "apellidoPat" => $_POST["APUsuario"],
                        "apellidoMat" => $_POST["AMUsuario"],
                        "sexo" => $_POST["sexUsuario"],
                        "email" => $_POST["emailUsuario"],
                        "telefono" => $_POST["telefUsuario"],
                        "departamento" => $_POST["DepUsuario"],
                        "provincia" => $_POST["ProvUsuario"],
                        "distrito" => $_POST["DistUsuario"],
                        "domicilio" => $_POST["DomUsuario"],
                        "tipoDocR" => $_POST["tDocRep"],
                        "nDocR" => $_POST["nDocRep"],
                        "nombresR" => $_POST["nomRep"],
                        "apellidoPatR" => $_POST["APRep"],
                        "apellidoMatR" => $_POST["AMRep"],
                        "rsocialR" => $_POST["rsRep"],
                        "emailRep" => $_POST["emailRep"],
                        "domicilioR" => $_POST["DomRep"],
                        "telefonoR" => $_POST["telefRep"],
                        "regsRep" => $_POST["representante"],
                        "tipoUsuario" => $_POST["tipoUsuario"],
                        "fechaOcurrencia" => $fechaOcurrencia,
                        "derecho" => $_POST["recCG"],
                        "causaEspecifica" => $_POST["recCE"],
                        "detalleReclamo" => $_POST["detReclamo"],
                        "autogenerado" => $_POST["autogenerated"],
                        "autoCorreo" => $_POST["repAuto"]
                    );
                    $rptRegReclamos = ReclamosModel::mdlRegistrarReclamo($datos);
                    if ($rptRegReclamos == "ok") {
                        $codigo = $codigoAutogen;
                        $correlativo = ControllerReclamo::ctrListarCorrelativo($codigo);
                        echo '<script>
                        function receivedDataPrmt(prmtData) {
                            var datos = new FormData();
                            datos.append("codigoReclamo", prmtData);
                            $.ajax({
                                url: "public/views/src/ajaxEnvioEmail.php",
                                method: "POST",
                                data: datos,
                                cache: false,
                                contentType: false,
                                processData: false,
                                dataType: "json"
                            });
                        }                        
                        receivedDataPrmt("' . $_POST["autogenerated"] . '");
                        
                                    Swal.fire({
                                    icon: "success",
                                    title: "' . $correlativo["mensaje"] . '",
                                    showConfirmButton: false,
                                    timer: 2500
                            });
                            function redirect(){
                                window.location = "registro-reclamo";
                            }
                            setTimeout(redirect,2500);
                            document.getElementById("formRegReclamo").reset();
                            </script>';
                    } else {
                        echo '<script>
                        Swal.fire({
                        icon: "error",
                        title: "Hubo un error al ingresar sus datos. Complete correctamente.",
                        showConfirmButton: false,
                        timer: 2500
                        });
                        function redirect(){
                            window.location = "registro-reclamo";
                        }
                        setTimeout(redirect,2500);
                        </script>';
                    }
                } elseif ($_POST["representante"] == 2) {
                    $datos = array(
                        "fechaReclamo" => $fechaRegReclamo,
                        "horaReclamo" => $horaRegReclamo,
                        "tipoDoc" => $_POST["tDocUsuario"],
                        "nDoc" => $_POST["nDocUsuario"],
                        "razonSocial" => $_POST["rsUsuario"],
                        "nombres" => $_POST["nomUsuario"],
                        "apellidoPat" => $_POST["APUsuario"],
                        "apellidoMat" => $_POST["AMUsuario"],
                        "sexo" => $_POST["sexUsuario"],
                        "email" => $_POST["emailUsuario"],
                        "telefono" => $_POST["telefUsuario"],
                        "departamento" => $_POST["DepUsuario"],
                        "provincia" => $_POST["ProvUsuario"],
                        "distrito" => $_POST["DistUsuario"],
                        "domicilio" => $_POST["DomUsuario"],
                        "tipoDocR" => $_POST["tDocRep"],
                        "nDocR" => $_POST["nDocRep"],
                        "nombresR" => $_POST["nomRep"],
                        "apellidoPatR" => $_POST["APRep"],
                        "apellidoMatR" => $_POST["AMRep"],
                        "rsocialR" => $_POST["rsRep"],
                        "emailRep" => $_POST["emailRep"],
                        "domicilioR" => $_POST["DomRep"],
                        "telefonoR" => $_POST["telefRep"],
                        "regsRep" => $_POST["representante"],
                        "tipoUsuario" => $_POST["tipoUsuario"],
                        "fechaOcurrencia" => $fechaOcurrencia,
                        "derecho" => $_POST["recCG"],
                        "causaEspecifica" => $_POST["recCE"],
                        "detalleReclamo" => $_POST["detReclamo"],
                        "autogenerado" => $_POST["autogenerated"],
                        "autoCorreo" => $_POST["repAuto"]
                    );

                    $rptRegReclamos = ReclamosModel::mdlRegistrarReclamo($datos);
                    if ($rptRegReclamos == "ok") {
                        $codigo = $codigoAutogen;
                        $correlativo = ControllerReclamo::ctrListarCorrelativo($codigo);
                        echo '<script>
                        
                        function receivedDataPrmt(prmtData) {
                            var datos = new FormData();
                            datos.append("codigoReclamo", prmtData);
                            $.ajax({
                                url: "public/views/src/ajaxEnvioEmail.php",
                                method: "POST",
                                data: datos,
                                cache: false,
                                contentType: false,
                                processData: false,
                                dataType: "json"
                            });
                        }  
                        receivedDataPrmt("' . $_POST["autogenerated"] . '");

                        Swal.fire({
                            icon: "success",
                            title: "' . $correlativo["mensaje"] . '",
                            showConfirmButton: false,
                            timer: 2500
                        });
                        function redirect(){
                            window.location = "registro-reclamo";
                        }
                        setTimeout(redirect,2500);
                        document.getElementById("formRegReclamo").reset();
                        </script>';
                    } else {
                        echo '<script>
                        Swal.fire({
                        icon: "error",
                        title: "Hubo un error al ingresar sus datos. Complete correctamente.",
                        showConfirmButton: false,
                        timer: 1800
                        });
                        function redirect(){
                            window.location = "registro-reclamo";
                        }
                        setTimeout(redirect,2500);
                        </script>';
                    }
                }
            } else {
                echo '<script>
                Swal.fire({
                icon: "error",
                title: "Ingrese los datos correctamente",
                showConfirmButton: false,
                timer: 2500
                });
                function redirect(){
                    window.location = "registro-reclamo";
                }
                setTimeout(redirect,2500);
                document.getElementById("formRegReclamo").reset();
                </script>';
            }
        }
    }

    static public function ctrListarCorrelativo($codigo)
    {
        $respuesta = ReclamosModel::mdlDevolverCorrelativo($codigo);
        return $respuesta;
    }

    static public function ctrListarParametros($tipo)
    {
        $respuesta = ReclamosModel::mdlListarParametros($tipo);
        return $respuesta;
    }
}
