<?php
require_once "../../../app/controllers/reclamosController.php";
require_once "../../../app/models/reclamosModel.php";

require "./../../views/util/phpmailer/Exception.php";
require "./../../views/util/phpmailer/PHPMailer.php";
require "./../../views/util/phpmailer/SMTP.php";
require "./../../views/util/tcpdf/tcpdf.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

class ajaxEnvioCorreo
{
    // public $tipoDoc;
    // public $nDoc;
    // public $razonSocial;
    // public $nombres;
    // public $apellidoPat;
    // public $apellidoMat;
    // public $sexo;
    // public $email;
    // public $telefono;
    // public $departamento;
    // public $provincia;
    // public $distrito;
    // public $domicilio;
    // public $tipoDocR;
    // public $nDocR;
    // public $nombresR;
    // public $apellidoPatR;
    // public $apellidoMatR;
    // public $rsocialR;
    // public $emailRep;
    // public $domicilioR;
    // public $telefonoR;
    // public $regsRep;
    // public $tipoUsuario;
    // public $fechaOcurrencia;
    // public $derecho;
    // public $causaEspecifica;
    // public $detalleReclamo;
    // public $autogenerado;
    // public $autoCorreo;
    public function ajaxEnviarCorreo()
    {
        // Listar Parametros
        $parametros = ControllerReclamo::ctrListarParametros(1);
        // Listar Parametros
        $cuerpoOficina = "<h1>XD</h1>";
        $destinoOficina = $parametros["correoParametro"];
        $asuntoOficina = "Información de Registro de Reclamo en Salud Virtual-HNSEB";
        $mailOficina1 = new PHPMailer(true);

        try {
            $mailOficina1->SMTPDebug = 0;
            $mailOficina1->isSMTP();
            $mailOficina1->Host = 'smtp-mail.outlook.com';
            $mailOficina1->SMTPAuth = true;
            $mailOficina1->Username = 'libroreclamacioneshnseb@outlook.com';
            $mailOficina1->Password = 'Sistemas2021+-+@';
            $mailOficina1->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mailOficina1->Port = 587;

            // Recipientes
            $mailOficina1->setFrom("libroreclamacioneshnseb@outlook.com", $parametros["detalleParametro"]);
            $mailOficina1->addAddress($destinoOficina);
            $mailOficina1->Subject = $asuntoOficina;
            $mailOficina1->isHTML(true);
            $mailOficina1->CharSet = "utf-8";
            $mailOficina1->Body = $cuerpoOficina;
            $mailOficina1->send();
        } catch (Exception $e) {
            echo "Hubo un error al enviar: {$mailOficina1->ErrorInfo}";
        }

        echo 1;
    }
}

$EnvioCorreo = new ajaxEnvioCorreo();

// $EnvioCorreo->fechaReclamo = $_POST["tDocUsuario"];
// $EnvioCorreo->tipoDoc = $_POST["tDocUsuario"];
// $EnvioCorreo->nDoc = $_POST["nDocUsuario"];
// $EnvioCorreo->razonSocial = $_POST["rsUsuario"];
// $EnvioCorreo->nombres = $_POST["nomUsuario"];
// $EnvioCorreo->apellidoPat = $_POST["APUsuario"];
// $EnvioCorreo->apellidoMat = $_POST["AMUsuario"];
// $EnvioCorreo->sexo = $_POST["sexUsuario"];
// $EnvioCorreo->email = $_POST["emailUsuario"];
// $EnvioCorreo->telefono = $_POST["telefUsuario"];
// $EnvioCorreo->departamento = $_POST["DepUsuario"];
// $EnvioCorreo->provincia = $_POST["ProvUsuario"];
// $EnvioCorreo->distrito = $_POST["DistUsuario"];
// $EnvioCorreo->domicilio = $_POST["DomUsuario"];
// $EnvioCorreo->tipoDocR = $_POST["tDocRep"];
// $EnvioCorreo->nDocR = $_POST["nDocRep"];
// $EnvioCorreo->nombresR = $_POST["nomRep"];
// $EnvioCorreo->apellidoPatR = $_POST["APRep"];
// $EnvioCorreo->apellidoMatR = $_POST["AMRep"];
// $EnvioCorreo->rsocialR = $_POST["rsRep"];
// $EnvioCorreo->emailRep = $_POST["emailRep"];
// $EnvioCorreo->domicilioR = $_POST["DomRep"];
// $EnvioCorreo->telefonoR = $_POST["telefRep"];
// $EnvioCorreo->regsRep = $_POST["representante"];
// $EnvioCorreo->tipoUsuario = $_POST["tipoUsuario"];
// $EnvioCorreo->fechaOcurrencia = $_POST["cajaFecha"];
// $EnvioCorreo->derecho = $_POST["recCG"];
// $EnvioCorreo->causaEspecifica = $_POST["recCE"];
// $EnvioCorreo->detalleReclamo = $_POST["detReclamo"];
// $EnvioCorreo->autogenerado = $_POST["autogenerated"];
// $EnvioCorreo->autoCorreo = $_POST["repAuto"];

$EnvioCorreo->ajaxEnviarCorreo();
